---
apiVersion: v1
kind: List
items:
- kind: Pod
  apiVersion: v1
  metadata:
    name: experimment
    namespace: front-door-ci
    labels:
      infra: exp
  spec:
    containers:
      - name: experimment
        image: quay.io/mmarusak/experimment:2
        ports:
          - name: ws
            containerPort: 5001

- kind: Service
  apiVersion: v1
  metadata:
    name: experimment-service
  spec:
    ports:
    - name: ws
      targetPort: 5001
      port: 5001
      protocol: TCP
    selector:
      infra: exp

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: experimment-route
  spec:
    to:
      kind: Service
      name: experimment-service
    port:
      targetPort: 5001
    tls:
      termination: edge
