---
apiVersion: v1
kind: List
items:
- kind: Pod
  apiVersion: v1
  metadata:
    name: cockpit-ws
    namespace: front-door-ci
    labels:
      infra: cockpit-ws
  spec:
    containers:
      - name: cockpit-ws
        image: quay.io/mmarusak/experimment:3
        ports:
          - name: ws
            containerPort: 8080
          - name: cockpit
            containerPort: 9090

- kind: Service
  apiVersion: v1
  metadata:
    name: cockpit-ws-service
  spec:
    ports:
    - name: ws
      targetPort: 8080
      port: 8080
      protocol: TCP
    - name: cockpit
      targetPort: 9090
      port: 9090
      protocol: TCP
    selector:
      infra: cockpit-ws

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: cockpit-ws-route
  spec:
    to:
      kind: Service
      name: cockpit-ws-service
    port:
      targetPort: 8080
    tls:
      termination: edge

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: cockpit
  spec:
    to:
      kind: Service
      name: cockpit-ws-service
    port:
      targetPort: 9090
    tls:
      termination: edge
